import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, RedirectToSignIn, SignedOut } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"

import '@stream-io/video-react-sdk/dist/css/styles.css';
import { ThemeProvider } from "../../providers/UiThemeProvider";


export const metadata: Metadata = {
  title: "ahameet",
  description: "Generated by Palawa Technology",
  icons: {icon: "/icon.png"}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${inter.className} bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-100`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          {children}
          <Toaster />
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
