import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, RedirectToSignIn, SignedOut } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"

import '@stream-io/video-react-sdk/dist/css/styles.css';


export const metadata: Metadata = {
  title: "ahameet v1",
  description: "Generated by Palawa Technology",
  icons: {icon: "/icon.png"}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${inter.className} bg-gray-900`}>
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
